package projectEuler;

public class even_Fibonacci_Numbers {
	public static void main(String[] args) {
		//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

			//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

			//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	
		int Vrijednost=0,Zbroj=1,Clan=2;
		int Niz[] = new int[40];
		Niz[0]=0;
		Niz[1]=1;
		
		for(int i=0;Vrijednost<4000000;i++) {
			Vrijednost=Niz[i]+Niz[i+1];
			if(Vrijednost<=4000000) {
				Niz[i+2]=Vrijednost;
				Clan++;
			}
			else {
				break;
			}
		}
		
		for(int i=0;i<Clan;i++) {
			System.out.print(Niz[i]+" ");
		}
		System.out.println();
		
		for(int i=1;i<Clan;i++) {
			if(Niz[i]%2==0) {
				System.out.print(Niz[i]+" ");
				Zbroj+=Niz[i];
			}
		}
		System.out.println();
		System.out.println(Zbroj);
		
		
	

			
			
	}


   }

		
		
	
	


